version: "3"
services:
  nginx:
    image: chreun/deploy_nginx
    depends_on:
      - php
    networks:
      - cgi
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8088:8088"
    volumes:
      - /data/log/nginx/:/var/log/nginx/
      - /data/www/Static/:/usr/share/nginx/html/
  php:
    depends_on:
      - mysql
      - redis
    image: easyswoole/easyswoole3
    working_dir: /var/www
    entrypoint: ['php', 'easyswoole', 'start']
    networks:
      - cgi
      - db
      - cache
    ports:
      - "9501:9501"
    restart: always
    volumes:
      - /data/www/:/easyswoole
  mysql:
    image: mysql:5.7.27
    networks:
      - db
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
    volumes:
      - /data/mysql/:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qaz123
  redis:
    image: redis:alpine
    restart: always
    networks:
      - cache
    volumes:
      - /data/redis:/data/

networks:
  cgi:
  db:
  cache: